---
kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
  namespace: hanfeng
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"
        # Port accesssible inside cluster
      port: 8080
      # Port to forward to inside cluster
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello-world
  namespace: hanfeng
spec:
  selector:
    matchLabels:
      app: hello-world 
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80
