apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lb-example
  name: hello-stateless-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lb-example
  template:
    metadata:
      labels:
        app: lb-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-stateless-world
        ports:
        - containerPort: 8080
