apiVersion: v1
kind: Pod
metadata:
  labels:
    test: healthcheck
  name: health-exec
spec:
  containers:
  - name: healthcheck
    image: k8s.gcr.io/busybox
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
